server:
#  servlet:
##    context-path: /URP
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/urp?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        allow:
        enabled: true
        reset-enable: false
        # 可视化界面地址和帐号密码 http://localhost:8080/URP/druid/sql.html
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"


file:
  upload:
    path: E:/FileServer/URPSM/

knife4j:
  enable: true

